[package]
name = "peer-quic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
quinn = "0.11.8"
tokio = { version = "1.45.1", features = ["full"] }

[build-dependencies]
rcgen = "0.13.2"
